import Head from 'next/head'
import Header from '../resources/frontend/components/Header'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import BinocularsIcon from '../resources/frontend/components/Icons/BinocularsIcon'
import ThumbsUpIcon from '../resources/frontend/components/Icons/ThumbsUpIcon'
import ChecklistIcon from '../resources/frontend/components/Icons/ChecklistIcon'
import ProductsCards from '../resources/frontend/components/ProductsCards'
import { useState } from 'react'
import { useRouter } from 'next/router'
import MobileNavbar from '../resources/frontend/components/MobileNavbar'
import TopButton from '../resources/frontend/components/TopButton'
import HeroImages from '../resources/frontend/components/HeroImages'

export default function Home (): React.ReactElement {
  const [searchQuery, setSearchQuery] = useState('')
  const router = useRouter()

  const handleChange = (e): void => {
    const { value } = e.target
    setSearchQuery(value)
  }

  const handleSubmit = (e): void => {
    e.preventDefault()
    const regexToAvoidEmpty = /(?<!\w)\s+(?!\w)/g
    if (searchQuery !== '' && !regexToAvoidEmpty.test(searchQuery)) {
      router.push('/yerba-mate?search=' + searchQuery)
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Ronda Matera</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <main className={styles.body}>
        <Header />
        <section className={styles.heroSection}>
          <HeroImages />
          <div className={styles.heroTextContainer}>
            <h1 className={styles.heroTitle}>
              Bienvenidos a la comunidad matera en España
            </h1>
            <h4 className={styles.heroSubtitle}>
              Aquí podés encontrar dónde comprar tu yerba preferida al mejor precio.
            </h4>
            <form onSubmit={handleSubmit} className={styles.searchBarContainer}>
              <input onChange={handleChange} className={styles.searchBar} type='text' placeholder='Buscar' />
              <button className={styles.searchBarBtn}>
                Search
              </button>
            </form>
          </div>
        </section>
        <section className={styles.infoSection}>
          <h2 className={styles.infoTitle}>
            ¿Qué encontrarás aquí?
          </h2>
          <div className={styles.infoCardsContainer}>
            <div className={styles.infoCard}>
              <div className={styles.iconContainer}>
                <BinocularsIcon />
              </div>
              <p>
                Recogemos información de sitios web que venden yerba mate en España y, de paso, te mostramos cual de ellas tiene el mejor precio.
              </p>
              <Link href='/yerba-mate' className={styles.infoCardBtn}>
                Ver productos
              </Link>
            </div>
            <div className={styles.infoCard}>
              <div className={styles.iconContainer}>
                <ThumbsUpIcon />
              </div>
              <p>
                Tenemos un recomendador, que te ayuda a elegir una yerba si es que nunca has probado el mate, o si tenes ganas de probar una yerba distinta, también te puede ser útil.
              </p>
              <Link href='/recomendador' className={styles.infoCardBtn}>
                El Recomendador
              </Link>
            </div>
            <div className={styles.infoCard}>
              <div className={styles.iconContainer}>
                <ChecklistIcon />
              </div>
              <p>
                Si no sabes como preparar un mate... ¡no te preocupes! Te explicamos de manera sencilla, paso a paso, como te puedes preparar unos ricos mates.
              </p>
              <Link href='/como-preparar-mate' className={styles.infoCardBtn}>
                ¿Cómo preparar un mate?
              </Link>
            </div>
          </div>
        </section>
        <section className={styles.recommendSection}>
          <h2 className={styles.recommendTitle}>
            Algunas Recomendadas
          </h2>
          <div>
            <ProductsCards keyword='normal' />
          </div>
        </section>
      </main>
      <TopButton />
      <MobileNavbar actual='home' />
    </div>
  )
}
